language: c
compiler: gcc
sudo: required
dist: trusty
cache:
  - apt

before_install:
  - sudo add-apt-repository ppa:vala-team -y
  - sudo add-apt-repository ppa:ricotz/testing -y
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake valac libgtk-3-dev libkeybinder-3.0-dev libxml2-utils gettext

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_TESTS=ON .
  - make
  - make test
  - # echo "deb http://archive.ubuntu.com/ubuntu/ xenial main universe multiverse restricted" > sources.list
  - # sudo mv sources.list /etc/apt/sources.list
  - # sudo apt-get update
  - sudo apt-get -y install checkinstall libx264-dev libvpx-dev yasm
  - sudo checkinstall --pkgname=app --pkgversion="1" --backup=no --fstrans=no --default --deldoc
  - wget -c "https://www.imagemagick.org/download/releases/ImageMagick-6.9.8-0.tar.xz"
  - tar xf ImageMagick-6.9.8-0.tar.xz
  - cd ImageMagick-6.9.8-0/
  - ./configure --prefix=/usr --enable-static=no --disable-docs --disable-deprecated --without-autotrace --without-bzlib --without-djvu --without-dps --without-fftw --without-fontconfig --without-fpx --without-freetype --without-gvc --without-jbig --without-jpeg --without-lcms --without-lzma --without-magick-plus-plus --without-openexr --without-openjp2 --without-pango --without-png --without-raqm --without-tiff --without-webp --without-wmf --without-x --without-xml --without-zlib
  - make
  - sudo checkinstall --pkgname=imagemagick --pkgversion="1" --backup=no --fstrans=no --default --deldoc
  - cd ..
  - wget -c "https://ffmpeg.org/releases/ffmpeg-3.2.4.tar.xz"
  - tar xf ffmpeg-3.2.4.tar.xz
  - cd ffmpeg-3.2.4
  - ./configure --prefix=/usr --disable-debug --disable-static --enable-gpl --enable-libvpx --enable-libx264 --enable-shared --enable-x11grab --disable-ffplay --disable-ffprobe --disable-ffserver --disable-doc --disable-everything --enable-decoder=libvpx_vp8 --enable-decoder=rawvideo --enable-encoder=libx264 --enable-encoder=libvpx_vp8 --enable-encoder=rawvideo --enable-encoder=pam --enable-demuxer=avi --enable-muxer=mp4 --enable-muxer=webm --enable-muxer=rawvideo --enable-filter=crop --enable-filter=scale --enable-protocol=file --enable-indev=x11grab_xcb
  - make
  - sudo checkinstall --pkgname=ffmpeg --pkgversion="1" --backup=no --fstrans=no --default --deldoc
  - cd ..
  - mkdir appdir ; cd appdir
  - dpkg -x ../app_1-1_amd64.deb . ; rm usr/local ; find .
  - cp ./usr/share/applications/*.desktop .
  - cp ./usr/share/icons/hicolor/256x256/apps/com.uploadedlobster.peek.png .
  - cd ..
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/3/linuxdeployqt-3-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/avconv -bundle-non-qt-libs # Workaround for https://github.com/probonopd/linuxdeployqt/issues/83
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/convert -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/peek -bundle-non-qt-libs
  - ( cd usr/share/glib-2.0/schemas/ ; glib-compile-schemas . )
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/peek -appimage
  - curl --upload-file ./Peek-*.AppImage https://transfer.sh/Peek-x86_64.AppImage

deploy:
  provider: launchpad
  slug: "~peek-developers/peek/+git/peek"
  oauth_token:
    secure: i6JfL4MPjIeZjs3a4hcVAP1ck86b0ENmMV5meKtUs8U7q8VH76Aaglr2SJQNqLmAC5SzLPoJuQoDZEwIAxQCmw1l1UjggjZnLcIXnWuJMJG6220Jel9OA9Q+mTM0Zk3yOzTOzwjTebIuUscb3h19Q2j9jU5Doo3703Z7b72B+nsVes14o5/xlfE8+LBeISeg0tsW8Ck54ssG10nzsaDV2GshJQG8uR1e6FQ2OLuDl1MqZ6TX9rY4GlS7Of8mgW4Pdp7ULrcgGGKzxOLXz0asNp+NuPkeO3qKsYghp/5/Y18TVgreIJ1Qf/OWcyrxAEdAqVznIXXh1iptpK/Czk7iudMtQqqnd/YzSUKUhzOw+hdyYQO2m8Z30WSTbhm+XcVxYkM4KwpFQ04F5RIFHGMA7pn1ihaELO9WbPKwp4e+L3C4lEs9kjoy+756wH7LUE5LILcN+iPnmpzg8SR4sx99te2eboh6nF822GagBd1BYNe0Rw2iftHbGC+NS846CEtFOKCKwIpfD0rC2aGAB1c63d5GSWSDE7YztmYzLS2Eq/xx4ELuQxUNY0/9P5fMQwt0R8Q3Osj70ZBm2mLN+9bER3QVruZ81Zbi0YEU9PGAQvGAxwwP18UDZpMiSR1beG33tXLfpDHR54dkJDT2yWxUa5ITTwvqiGEVzqz2bPqklsM=
  oauth_token_secret:
    secure: ZQllTTeB8oWeoQ+O+TKoI7VagUyAMuFGGUfeuGGVvwR0i0SnR4m+RfA39iwlvqSGO33vMxGycj741bgJmCmslyIteTkgASMyPEiqHA37SRh6IIQQT9wInw8MV17Biykj+rgEryv+b7+6rPLXtESC144/1I5YuGYTuNIGQJZmCUdeZMFkM7XR/h41vXahaZPjJio1t/d/m36JzkP1urGZz1yFvnV6AJHrWP6JOFG7r4+7c4EKELo/jnsWjfxfcSRyQX3DkEfUcSSgn9ZA0n6i9Tq2AhaXYLnQXCLm1DAroBWdf3OHfi5PBsN4hraRIweB1aLilpfDuV2Q7WYVlvt6KfCR8GFSJR+vDX9KjhiqwvyqKZdkoe1vIhcdeE1vqXjW3b6YYnsBVi2ccY4qQZhwOuTz3KoygPSqpaFAeRs7jyu9kYRAjJvxgLY3bSyRYWSfHYLTGgxB/ZTl4oM5AUOFYXRcegiqpeGecCrKGBnG8c+YiYq+O/otI2RSlfV5k0q0UNDJRDxOo7ifZT9SdvKnDOqBpWMlKOA3NS6jItwcfDKwdjcZM4uer6VxsYOTS5AaJlm2SIjSrY1tdrC3F9VvZ+OX2tWluMtqJPW5GGspUfkoyrd+Udc8vDID1/ZutbtxA03BC2YSPbZlcWsw4klRv1h7eOfN5n52EQM9cLaPeg4=
